_format_version: "3.0"
_transform: true

services:
  - name: ms-identity
    url: http://host.docker.internal:3001
    routes:
      - name: identity-route
        paths:
          - /auth
        strip_path: false
  - name: ms-academic
    url: http://host.docker.internal:3002
    routes:
      - name: academic-route
        paths:
          - /academic
        strip_path: false
  - name: ms-hr
    url: http://host.docker.internal:3003
    routes:
      - name: hr-route
        paths:
          - /hr
        strip_path: false
  - name: ms-finance
    url: http://host.docker.internal:3004
    routes:
      - name: finance-route
        paths:
          - /finance
        strip_path: false
  - name: ms-notification
    url: http://host.docker.internal:3005
    routes:
      - name: notification-route
        paths:
          - /notifications
        strip_path: false

plugins:
  - name: rate-limiting
    config:
      second: 5
      hour: 10000
      policy: local
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
        - x-tenant-id
      exposed_headers:
        - X-Auth-Token
        - Authorization
      credentials: true
      max_age: 3600
