#!/bin/bash
# =============================================================================
# GestorEscolar — First-time setup script
# Automates: .env file creation, secret generation, migration execution
#
# Usage:
#   ./scripts/setup.sh              # interactive (prompts for Google credentials)
#   ./scripts/setup.sh --no-google  # skip Google OAuth prompts (CI / no OAuth)
#   ./scripts/setup.sh --force      # overwrite existing .env files
# =============================================================================

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

FORCE=false
NO_GOOGLE=false

for arg in "$@"; do
  case $arg in
    --force)    FORCE=true ;;
    --no-google) NO_GOOGLE=true ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

log()  { echo -e "${BLUE}[setup]${NC} $*"; }
ok()   { echo -e "${GREEN}[setup]${NC} $*"; }
warn() { echo -e "${YELLOW}[setup]${NC} $*"; }
err()  { echo -e "${RED}[setup]${NC} $*"; exit 1; }

# ─── Dependency check ────────────────────────────────────────────────────────
command -v node >/dev/null 2>&1 || err "node is required but not found"

# ─── Secret generators ───────────────────────────────────────────────────────
gen_secret() {
  node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))"
}

gen_password() {
  node -e "process.stdout.write(require('crypto').randomBytes(16).toString('base64url'))"
}

# ─── Step 1: Generate shared secrets ─────────────────────────────────────────
log "Generating shared secrets..."

JWT_SECRET=$(gen_secret)
KONG_JWT_SECRET=$(gen_secret)
POSTGRES_PASSWORD=$(gen_password)
RABBITMQ_PASS=$(gen_password)
GRAFANA_ADMIN_PASSWORD=$(gen_password)

ok "Secrets generated."

# ─── Step 2: Google OAuth credentials ────────────────────────────────────────
if [ "$NO_GOOGLE" = false ]; then
  echo ""
  warn "Google OAuth credentials are required for login to work."
  warn "Get them from: https://console.cloud.google.com/apis/credentials"
  echo ""
  read -rp "  GOOGLE_CLIENT_ID     : " GOOGLE_CLIENT_ID
  read -rp "  GOOGLE_CLIENT_SECRET : " GOOGLE_CLIENT_SECRET
  echo ""
else
  GOOGLE_CLIENT_ID="REPLACE_WITH_GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET="REPLACE_WITH_GOOGLE_CLIENT_SECRET"
  warn "--no-google: placeholder values written for Google credentials."
fi

# ─── Step 3: Write root .env ──────────────────────────────────────────────────
ROOT_ENV="$ROOT_DIR/.env"
write_root_env() {
  cat > "$ROOT_ENV" <<EOF
# Auto-generated by scripts/setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file.

# PostgreSQL
POSTGRES_USER=admin
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=gestor_escolar

# RabbitMQ
RABBITMQ_USER=gestor_user
RABBITMQ_PASS=$RABBITMQ_PASS

# Grafana
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD

# Kong JWT (must match JWT_SECRET in ms-identity)
KONG_JWT_SECRET=$KONG_JWT_SECRET

# Frontend URL
FRONTEND_URL=http://localhost:5173
EOF
}

if [ "$FORCE" = true ] || [ ! -f "$ROOT_ENV" ]; then
  write_root_env
  ok "Written: .env"
else
  warn "Skipping .env (already exists — use --force to overwrite)"
fi

# ─── Step 4: Write per-service .env files ─────────────────────────────────────
write_service_env() {
  local service=$1
  local port=$2
  local extra=$3
  local target="$ROOT_DIR/apps/$service/.env"

  if [ "$FORCE" = false ] && [ -f "$target" ]; then
    warn "Skipping apps/$service/.env (already exists)"
    return
  fi

  cat > "$target" <<EOF
# Auto-generated by scripts/setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file.
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_USER=admin
DATABASE_PASSWORD=$POSTGRES_PASSWORD
DATABASE_NAME=gestor_escolar

JWT_SECRET=$JWT_SECRET

RABBITMQ_URL=amqp://gestor_user:$RABBITMQ_PASS@rabbitmq:5672

NODE_ENV=development
PORT=$port
$extra
EOF
  ok "Written: apps/$service/.env"
}

write_service_env "ms-academic"     "3002" ""
write_service_env "ms-hr"           "3003" ""
write_service_env "ms-finance"      "3004" ""
write_service_env "ms-notification" "3005" ""

# ms-identity needs extra fields
IDENTITY_ENV="$ROOT_DIR/apps/ms-identity/.env"
if [ "$FORCE" = true ] || [ ! -f "$IDENTITY_ENV" ]; then
  cat > "$IDENTITY_ENV" <<EOF
# Auto-generated by scripts/setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file.
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_USER=admin
DATABASE_PASSWORD=$POSTGRES_PASSWORD
DATABASE_NAME=gestor_escolar

JWT_SECRET=$JWT_SECRET

GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
GOOGLE_CALLBACK_URL=http://localhost:8000/auth/google/callback

RABBITMQ_URL=amqp://gestor_user:$RABBITMQ_PASS@rabbitmq:5672

REDIS_HOST=redis
REDIS_PORT=6379

NODE_ENV=development
FRONTEND_URL=http://localhost:5173
COOKIE_DOMAIN=
PORT=3001
EOF
  ok "Written: apps/ms-identity/.env"
else
  warn "Skipping apps/ms-identity/.env (already exists)"
fi

# ─── Step 5: Run migrations ───────────────────────────────────────────────────
echo ""
log "Step 5/5 — Running TypeORM migrations..."
log "Waiting for PostgreSQL to be reachable..."

# Wait until postgres is accepting connections (max 30s)
RETRIES=15
until docker exec schooldb pg_isready -U admin -d gestor_escolar -q 2>/dev/null; do
  RETRIES=$((RETRIES - 1))
  if [ $RETRIES -le 0 ]; then
    warn "PostgreSQL not reachable — skipping migrations."
    warn "Run manually after 'docker compose up -d':"
    warn "  cd apps/ms-identity && npm run migration:run"
    warn "  cd apps/ms-academic && npm run migration:run"
    warn "  cd apps/ms-hr       && npm run migration:run"
    warn "  cd apps/ms-finance  && npm run migration:run"
    exit 0
  fi
  sleep 2
done

ok "PostgreSQL is ready."

run_migration() {
  local service=$1
  log "Running migrations for $service..."
  (cd "$ROOT_DIR/apps/$service" && npm run migration:run 2>&1) && ok "$service migrations applied." \
    || warn "$service migration failed (schema may already be up to date)"
}

run_migration "ms-identity"
run_migration "ms-academic"
run_migration "ms-hr"
run_migration "ms-finance"

echo ""
ok "================================================================"
ok " Setup complete!"
ok "================================================================"
echo ""
echo -e "  Next step: ${YELLOW}./scripts/start-local.sh${NC}"
echo ""
